# Generated by Django 2.1.4 on 2019-08-16 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('write', models.TextField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('good_num', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='news',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('con', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('write_con', models.TextField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('good_num', models.PositiveIntegerField()),
                ('r_com', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app3.comment')),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=10)),
                ('head', models.ImageField(upload_to='img')),
            ],
        ),
        migrations.AddField(
            model_name='reply',
            name='r_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app3.user'),
        ),
        migrations.AddField(
            model_name='news',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app3.user'),
        ),
        migrations.AddField(
            model_name='comment',
            name='c_news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app3.news'),
        ),
        migrations.AddField(
            model_name='comment',
            name='c_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app3.user'),
        ),
    ]
